/* ==========================================================================
   Lights Out — toggle a cell and its orthogonal neighbours, clear the board.
   Includes a guaranteed-solvable generator and a hint solver.
   ========================================================================== */
(function (win, doc) {
  "use strict";

  var $ = SG.$, $$ = SG.$$;
  var gridEl = $("[data-grid]");
  if (!gridEl) return;

  var GAME = "lightsout";

  var LEVELS = {
    easy:   { size: 4, label: "4 x 4" },
    classic:{ size: 5, label: "5 x 5" },
    hard:   { size: 7, label: "7 x 7" }
  };

  var state = {
    cfg: LEVELS[SG.store.get("lightsout:level", "classic")] || LEVELS.classic,
    lamps: [],
    cells: [],
    moves: 0,
    over: false,
    started: false,
    hint: -1
  };

  var hud = SG.hud({ moves: 1, lit: 1, size: 1, best: 1 });

  /* ---------------------------------------------------------------- model */
  /* Lamps are stored in a plain array: a 7 x 7 board is 49 cells, which does
     not fit in JavaScript's 32-bit bitwise operators, so no bitmask here. */
  function idx(r, c) { return r * state.cfg.size + c; }
  function rowOf(i) { return Math.floor(i / state.cfg.size); }
  function colOf(i) { return i % state.cfg.size; }
  function lit(i) { return state.lamps[i] === 1; }

  /* Pressing a lamp flips itself plus its four orthogonal neighbours. */
  function pressMask(lamps, i) {
    var s = state.cfg.size;
    var r = rowOf(i), c = colOf(i);
    var flip = [i];
    if (r > 0) flip.push(idx(r - 1, c));
    if (r < s - 1) flip.push(idx(r + 1, c));
    if (c > 0) flip.push(idx(r, c - 1));
    if (c < s - 1) flip.push(idx(r, c + 1));
    for (var k = 0; k < flip.length; k++) lamps[flip[k]] ^= 1;
    return lamps;
  }

  /* The puzzle is generated by starting from all-lights-off and applying
     random presses, so the board is always solvable by definition. */
  function generate() {
    var s = state.cfg.size;
    var total = s * s;
    var lamps = [];
    for (var i = 0; i < total; i++) lamps.push(0);
    var presses = Math.max(4, Math.round(total * 0.28));
    for (var p = 0; p < presses; p++) pressMask(lamps, SG.randInt(0, total - 1));
    /* never deal an already-solved board */
    if (lamps.every(function (v) { return v === 0; })) pressMask(lamps, SG.randInt(0, total - 1));
    return lamps;
  }

  function litCount() {
    var n = 0;
    for (var i = 0; i < state.lamps.length; i++) if (state.lamps[i]) n++;
    return n;
  }

  function isSolved() {
    for (var i = 0; i < state.lamps.length; i++) if (state.lamps[i]) return false;
    return true;
  }

  /* --------------------------------------------------------------- hint */
  /* Chasing the lights top-down: the first lit lamp outside the bottom row
     can only be cleared by pressing the cell directly beneath it, so that
     press is guaranteed to be part of the solution. */
  function findHint() {
    var s = state.cfg.size;
    for (var r = 0; r < s - 1; r++) {
      for (var c = 0; c < s; c++) {
        if (lit(idx(r, c))) return idx(r + 1, c);
      }
    }
    return null;
  }

  /* ------------------------------------------------------------------ dom */
  function build() {
    var s = state.cfg.size;
    gridEl.style.setProperty("--size", s);
    gridEl.innerHTML = "";
    state.cells = [];
    for (var i = 0; i < s * s; i++) {
      var b = doc.createElement("button");
      b.type = "button";
      b.className = "lo-cell";
      b.setAttribute("data-i", i);
      state.cells.push(b);
      gridEl.appendChild(b);
    }
  }

  function render() {
    for (var i = 0; i < state.cells.length; i++) {
      var on = lit(i);
      state.cells[i].classList.toggle("is-on", on);
      state.cells[i].setAttribute("aria-pressed", String(on));
      var r = rowOf(i), c = colOf(i);
      state.cells[i].setAttribute("aria-label", "Row " + (r + 1) + " column " + (c + 1) + ", " + (on ? "on" : "off"));
      state.cells[i].classList.toggle("is-hint", state.hint === i);
    }
  }

  function paintHud() {
    hud.set("moves", state.moves);
    hud.set("lit", litCount());
    hud.set("size", state.cfg.size + "x" + state.cfg.size);
    var b = SG.scores.get("lightsout:" + state.cfg.size + "x" + state.cfg.size);
    hud.set("best", b ? b.label : "—");
  }

  function reset() {
    state.lamps = generate();
    state.moves = 0;
    state.over = false;
    state.started = false;
    state.hint = -1;
    build();
    render();
    paintHud();
    $("[data-status]").textContent = "Turn every lamp off.";
  }

  function press(i) {
    if (state.over) return;
    pressMask(state.lamps, i);
    state.moves += 1;
    state.hint = -1;
    if (!state.started) { state.started = true; SG.stats.play(GAME); }
    SG.sound.play("flip");
    render();
    paintHud();

    if (isSolved()) {
      state.over = true;
      SG.stats.win(GAME);
      var res = SG.scores.submitLow("lightsout:" + state.cfg.size + "x" + state.cfg.size, state.moves, state.moves + " moves");
      SG.sound.chord("bigwin", [0, 4, 7, 12]);
      SG.confetti.burst(150);
      $("[data-status]").textContent = "Solved in " + state.moves + " moves.";
      SG.toast({
        icon: res.isBest ? "🏅" : "💡",
        title: res.isBest ? "New best: " + state.moves + " moves" : "Solved in " + state.moves,
        sub: state.cfg.label + " lights out board"
      });
      paintHud();
    }
  }

  /* -------------------------------------------------------------- events */
  gridEl.addEventListener("click", function (e) {
    var b = e.target.closest(".lo-cell");
    if (!b) return;
    press(parseInt(b.getAttribute("data-i"), 10));
  });

  $$("[data-new]").forEach(function (b) { b.addEventListener("click", reset); });

  var hintBtn = $("[data-hint]");
  if (hintBtn) {
    hintBtn.addEventListener("click", function () {
      if (state.over) { reset(); return; }
      state.hint = findHint();
      render();
      if (state.hint === null) {
        $("[data-status]").textContent = "This board is already clear — press New to deal a new one.";
      } else {
        $("[data-status]").textContent = "Try the highlighted lamp.";
      }
    });
  }

  function bindSeg(attr, cb) {
    var groups = [];
    $$("button[" + attr + "]").forEach(function (b) {
      if (groups.indexOf(b.parentNode) === -1) groups.push(b.parentNode);
    });
    groups.forEach(function (g) {
      g.addEventListener("click", function (e) {
        var btn = e.target.closest("button[" + attr + "]");
        if (!btn) return;
        $$("button[" + attr + "]").forEach(function (o) {
          o.setAttribute("aria-pressed", String(o.getAttribute(attr) === btn.getAttribute(attr)));
        });
        cb(btn.getAttribute(attr));
      });
    });
  }

  bindSeg("data-level", function (v) {
    state.cfg = LEVELS[v] || LEVELS.classic;
    SG.store.set("lightsout:level", v);
    reset();
  });

  doc.addEventListener("keydown", function (e) {
    var t = e.target;
    if (t && (t.tagName === "INPUT" || t.tagName === "TEXTAREA" || t.isContentEditable)) return;
    if (e.key === "n" || e.key === "N") { e.preventDefault(); reset(); }
    else if (e.key === "h" || e.key === "H") {
      e.preventDefault();
      if (hintBtn) hintBtn.click();
    }
  });

  /* ---------------------------------------------------------------- boot */
  $$("button[data-level]").forEach(function (o) {
    var key = (LEVELS[o.getAttribute("data-level")] || {}).label;
    o.setAttribute("aria-pressed", String(key === state.cfg.label));
  });
  reset();
})(window, document);
